module PubQuiz (
  RandomPubQuiz,
  randomPubQuiz
  ) where

import Logic

data PubQuestion = PubQuestion {
    question :: String
  , answer :: String
}

randomPubQuiz :: RandomPubQuiz
randomPubQuiz = RandomPubQuiz questions

data RandomPubQuiz = RandomPubQuiz [(String, String)]

instance QuestionMaker RandomPubQuiz where
  generateQuestion seed IdentifyMultipleType (RandomPubQuiz questions) = do
    questionShortlist <- rndSelect seed questions 10
    return $ Just (Associate "Answer these questions" questionShortlist)
  generateQuestion seed IdentifyTextType (RandomPubQuiz questions) = do
    question <- chooseFromList seed questions
    return $ Just (uncurry (IdentifyText "Answer this question") question Nothing)
  generateQuestion _ _ _ = return Nothing

questions :: [(String, String)]
questions = [
  ("What country owns the Canary Islands?", "Spain"),
  ("What river flows through the Grand Canyon in the USA?", "Colorado"),
  ("Which English football club won the League and FA Cup \"double\" in 1986?", "Liverpool"),
  ("What is the lightest of all the elements and has the atomic number 1?", "Hydrogen"),
  ("Before the French Revolution in 1789, who is reported to have said \"Let them eat cake\"?", "Marie Antoinette"),
  ("Which note does an orchestra tune to?", "A"),
  ("Who was voted European Footballer of the Year for 2000?", "Luis Figo"),
  ("What is the capital city of Morocco?", "Rabat"),
  ("In the world of weaponry, what do the initials ICBM stand for?", "Inter-continental Ballistic Missile"),
  ("In the medical world what do the initials ENT stand for?", "Ear Nose and Throat"),
  ("What country has an area of approximately 3.85 million square miles, a population of 29 million and her flag is coloured red and white?", "Canada"),
  ("Which author and comedian has released the novels \"Time for Bed\" and \"Whatever Love Means\"?", "David Baddiel"),
  ("Which Commonwealth country had the Prime Ministers Bill McMahon, Edward Whitlam and John Frasier in the 1970s?", "Australia"),
  ("What colour light is displayed from the starboard side of a ship?", "Green"),
  ("Who was the leader of the USSR when Yuri Gagarin became the first man to go into space?", "Nikita Krushchev"),
  ("Who played Edmund Blackadder in the BBC comedy series Blackadder?", "Rowan Atkinson"),
  ("Which mountain range runs along the west coast of South America for over 4,000 miles?", "Andes"),
  ("What is the SI unit for time?", "Second"),
  ("Which male athlete won 4 gold medals at the 1984 Los Angeles Olympics for the 100 metres, 200 metres, 400 metre relay and the long jump?", "Carl Lewis"),
  ("At which battle was Richard III slain?", "Bosworth Field"),
  ("What is the longest river in Great Britain?", "The Severn"),
  ("What is the patella bone better known as?", "The kneecap"),
  ("Which book features the characters Passepartout, Mr Fix and Aouda?", "Around The World In Eighty Days"),
  ("In the song, Solomon Grundy was born on Monday, what happened to him on Thursday?", "Took ill"),
  ("Who was the leader of the USSR during World War Two?", "Joseph Stalin"),
  ("What is the fourth planet from the Sun?", "Mars"),
  ("What game's name comes from the French for \"little wheel\"?", "Roulette"),
  ("Who won the men's 100 metres gold medal at the 2000 Olympic Games?", "Maurice Greene"),
  ("What nation won the men's football gold medal at the 2000 Olympic Games?", "Cameroon"),
  ("What country has an area of approximately 7.7 million square kilometres, a population of 18 million and her flag comprises the colours red, white and blue?", "Australia"),
  ("Who wrote the classic thriller The Thirty-Nine Steps?", "John Buchan"),
  ("Which religion features The Four Noble Truths?", "Buddhism"),
  ("Who designed the spectacular Church of the Holy Family and the Casa Mila block of flats, both in Barcelona?", "Gaudi"),
  ("What type of animal is the oriole?", "Bird"),
  ("In which US state are the cities of Las Vegas and Reno?", "Nevada"),
  ("Who defeated the Persian king Darius III at the Battle of Issus in 333 BC?", "Alexander the Great"),
  ("What is the chemical symbol for sodium?", "Na"),
  ("Who released the album \"All That You Can't Leave Behind\" in 2000?", "U2"),
  ("Who won the Best Actor Oscar for his performance as Judah Ben Hur in the 1959 epic Ben-Hur?", "Charlton Heston"),
  ("Who played JR Ewing in the TV series Dallas?", "Larry Hagman"),
  ("How many wives of Henry VIII were beheaded?", "2"),
  ("Where were the 1992 Summer Olympic Games held?", "Barcelona, Spain"),
  ("Who wrote Tarzan of the Apes in 1912?", "Edgar Burroughs"),
  ("Which Japanese martial art translates into English as \"empty hand\"?", "Karate"),
  ("Who played the Toymaker in the 1968 film Chitty Chitty Bang Bang?", "Benny Hill"),
  ("Who wrote the novel Chitty Chitty Bang Bang : The Magical Car?", "Ian Fleming"),
  ("What is the chemical symbol for Copper?", "Cu"),
  ("In what year was Margaret Thatcher elected as Britain's first female Prime Minister?", "1979"),
  ("Which of these countries does NOT border the Russian Federation Georgia, Armenia, Azerbaijan or Latvia?", "Armenia"),
  ("What number is represented by the Roman numeral XLV?", "45"),
  ("In which field was Frenchman Eugene Ferdinand Victor Delacroix famous in the 19th Century?", "Painting"),
  ("In physics, what letter is used to represent to fundamental constant that is equal to \"9.80665 metres per second squared\"?", "g"),
  ("What is the capital of the US State of Florida?", "Tallahassee"),
  ("What sport is played in the USA by the Minnesota Timberwolves, Cleveland Cavaliers and Houston Rockets?", "Basketball"),
  ("What is the orbital period of Halley's Comet?", "76 years"),
  ("At which battle on August 1st 1798 did Nelson destroy the French fleet, 7 years before doing it again at the Battle of Trafalgar?", "Battle of the Nile"),
  ("What football club play their home games at Brunton Park?", "Carlisle United"),
  ("Which US state's flag has a Union Jack in the canton?", "Hawaii"),
  ("From which plant do we get Vanilla?", "Orchid"),
  ("Who wrote the novel Black Beauty, first published in 1877?", "Anna Sewell"),
  ("Which metallic element has the chemical symbol Pb and atomic number 82?", "Lead"),
  ("Which American city is known as 'the city of brotherly love'?", "Philadelphia"),
  ("Who preceeded Margaret Thatcher as Prime Minister of the United Kingdom?", "James Callaghan"),
  ("Odin, a one-eyed bearded old man was the most powerful god in which mythology?", "Norse"),
  ("What is the name of the galaxy our Solar System is in?", "The Milky Way"),
  ("What country did ex-Liverpool goalkeeper Bruce Grobbelaar represent?", "Zimbabwe"),
  ("What flag does a ship traditionally fly to indicate it is about to set sail?", "The Blue Peter"),
  ("What is the capital city of Iran?", "Tehran"),
  ("If diamond is for the 60th and gold for the 50th, what is used to celebrate the 20th wedding anniverary?", "China"),
  ("Which English scientist discovered Sodium, Potassium, Barium, Calcium and Magnesium?", "Sir Humphrey Davy"),
  ("What term is used for the male voice higher than bass and lower than tenor?", "Baritone"),
  ("Which Welsh city is called Abertawe in Welsh?", "Swansea"),
  ("What is the longest river in Asia?", "Yangtze"),
  ("With which instrument is American B B King chiefly associated?", "Guitar"),
  ("Who won the 1992 FA Cup Final?", "Liverpool"),
  ("In Greek mythology, who killed Achilles?", "Paris"),
  ("Who plays Mike Baldwin in the soap opera Coronation Street?", "Johnny Briggs"),
  ("Which racecourse in the Republic of Ireland is also a palindrome?", "Navan"),
  ("What town was the birthplace of William Shakespeare?", "Stratford-upon-Avon"),
  ("What fruit is also known as the 'Love Apple'?", "Tomato"),
  ("What is the name of the Israeli Secret Service?", "Mossad"),
  ("Adam West was most famous for playing which comic book character on television?", "Batman"),
  ("What sport is contested between the United States and Great Britain for the Walker Cup?", "Golf"),
  ("How many squares are on a chessboard?", "64"),
  ("How was Eric Hugh Blair, born in 1903, better known?", "George Orwell"),
  ("Who was American president when Neil Armstrong first walked on the moon?", "Richard Nixon"),
  ("Which cast member of the TV comedy show Friends also starred in the movie Scream?", "Courteney Cox"),
  ("In North America, what sport is played by the New Jersey Devils and the Florida Panthers?", "Ice Hockey"),
  ("What was the former name of the country Mynamar?", "Burma"),
  ("Which author wrote the \"Foundation\" series of science fiction novels?", "Isaac Asimov"),
  ("What was the name of the time machine Doctor Who travelled in?", "TARDIS"),
  ("How many players in total are on the field at the start of a regular game of Gaelic Football?", "30"),
  ("What is Britain's largest freshwater fish?", "The Pike"),
  ("What is the chemical symbol for Sodium?", "Na"),
  ("How many stars are on the flag of the United States?", "50"),
  ("Which actor has played Ken Barlow on Coronation Street for over 40 years?", "William Roach"),
  ("What country is completely landlocked within the Republic of South Africa?", "Lesotho"),
  ("What is the first part of JRR Tolkien's \"The Lord of the Rings\" trilogy called?", "The Fellowship of the Ring"),
  ("What European capital city stands on the River Tiber?", "Rome"),
  ("Who was disqualified and stripped of his gold medal for the 100 metres at the 1988 Olympic Games?", "Ben Johnson"),
  ("What American author wrote the classics \"East of Eden\", \"Of Mice and Men\" and \"The Grapes of Wrath\"?", "John Steinbeck"),
  ("In which US State is Kilauea, the world's most active volcano?", "Hawaii"),
  ("In distance, which planet is sixth furthest from the Sun?", "Saturn"),
  ("What is the well known Japanese word for \"empty orchestra\"?", "Karaoke"),
  ("What is the official name of the bottom 9 miles (15 KM) of the Earth's atmosphere?", "Troposphere"),
  ("Anubis is the god of funerals who transports the souls of the dead to the other world in which ancient civilization?", "Egyptian"),
  ("What is the chemical symbol for Potassium?", "K"),
  ("Which renaissance artist painted Primavera and The Birth of Venus?", "Botticelli"),
  ("The island of Bahrain is connected by a causeway to which country?", "Saudi Arabia"),
  ("What country's flag (bizzarly) has a garden hoe and a Kalashnikov rifle inside a star?", "Mozambique"),
  ("Which Italian author published Pinocchio in 1880?", "Carlo Collodi"),
  ("Which scientist published the ground breaking book \"Principia Mathematica\" in the 17th Century?", "Isaac Newton"),
  ("Who was the last Tsar of Russia, who was murdered along with all his family by Bolshevik guards?", "Nicholas II"),
  ("What is the more common name for ascorbic acid?", "Vitamin C"),
  ("In computing, what does RAM stand for?", "Random Access Memory"),
  ("By area, what is the largest country in Africa?", "Sudan"),
  ("What American band have released the albums \"Out of Time\" and \"Automatic for the People\"?", "R.E.M."),
  ("Which country won the football World Cup in 1934 and 1938?", "Italy"),
  ("How many minutes of play are in an American football match?", "60"),
  ("Which company produces the computer operating system Windows?", "Microsoft"),
  ("Which novel, first published in 1719, is based on the real-life exploits of Alexander Selkirk?", "Robinson Crusoe"),
  ("What is the deepest lake in the world, with depths over 1,600 metres?", "Baikal"),
  ("Complete this advertising slogan \"Murraymints, Murraymints...\"?", "Too good to hurry mints"),
  ("Which country's flag consists of just the colour green?", "Libya"),
  ("Who played Vivien in the BBC comedy The Young Ones?", "Adrian Edmondson"),
  ("In which European country is Transylvania?", "Romania"),
  ("Who wrote the novel Jurassic Park, which the Spielberg film was based on?", "Michael Crichton"),
  ("What is the square root of 121?", "11"),
  ("How many dimes are in a US dollar?", "10"),
  ("What is the chemical symbol for Gold?", "Au"),
  ("Which television character has the car registration plate FAB1?", "Lady Penelope"),
  ("Which king was killed at the Battle of Bosworth Field in 1485?", "Richard III"),
  ("Who composed the ballets \"The Nutcracker\" and \"Swan Lake\"?", "Peter Tchaikovsky"),
  ("If you suffered from 'arachnophobia', what would you have an irrational fear of?", "Spiders"),
  ("What city does Sugar Loaf mountain overlook?", "Rio de Janeiro"),
  ("Which gas is the most abundant in air, making up over 77%?", "Nitrogen"),
  ("Which of William Shakespeares' plays has the most lines?", "Hamlet"),
  ("Who directed the movies \"Jaws\", \"Schindler's List\" and \"Jurassic Park\"?", "Steven Spielberg"),
  ("What is the largest country, by area, in the European Union?", "France"),
  ("Who wrote \"Three Men In A Boat\"?", "Jerome K Jerome"),
  ("Aboard which US warship did the Japanese sign their surrender in World War II?", "USS Missouri"),
  ("What is the minimum number of points required to win a tennis tie-break?", "7"),
  ("How many stars are on the flag of the European Union?", "12"),
  ("What was the name of the theatre where US president Abraham Lincoln was assassinated?", "Ford's"),
  ("Which American criminal was named \"Public enemy number one\" by the FBI in the 1930's?", "John Dillenger"),
  ("What do the initials FBI stand for?", "Federal Bureau of Investigation"),
  ("Which car company has manufactured models called Scorpio and Orion?", "Ford"),
  ("In which year was Nelson Mandela released in South Africa, after 27 years in prison?", "1990"),
  ("Which band released the album \"Kid A\" in 2000?", "Radiohead"),
  ("Which US State has the nickname \"The Sunshine State\"?", "Florida"),
  ("Which mountain range separates France and Spain?", "Pyrenees"),
  ("When Neil Armstrong stepped onto the moon and said his famous pre-written line, he missed out an important word. What word was it?", "a"),
  ("Who won the Nobel Prize for physics in 1901 for discovering X-Rays?", "Rontgen"),
  ("How is Nitrous Oxide better known?", "Laughing gas"),
  ("Which famous author proclaimed at New York customs, \"I have nothing to declare but my genius\"?", "Oscar Wilde"),
  ("Who preceded Margaret Thatcher as Prime Minister of Great Britain?", "James Callaghan"),
  ("Where were the 1970 football World Cup finals held?", "Mexico"),
  ("In books by JRR Tolkien, what kind of creatures are Bilbo and Frodo Baggins?", "Hobbits"),
  ("Which Italian city is home of the car manufacturer Fiat?", "Turin"),
  ("What do the French call the English Channel?", "Le Manche"),
  ("In which year of the 1940's did the D-Day landings take place on the coast of Normandy?", "1944"),
  ("Who starred in the films \"Some Like It Hot\", \"Bus Stop\" and \"The Seven Year Itch\"?", "Marilyn Monroe"),
  ("What is the largest mammal on Earth?", "Blue whale"),
  ("What is North America's highest mountain?", "Mount McKinley"),
  ("What is the chemical symbol for tin?", "Sn"),
  ("What are Corvettes, Sloops and Brigantines?", "Sailing ships"),
  ("Until the introduction of the Euro, what is the unit of currency in Austria?", "Schilling"),
  ("Which African country's capital city is Luanda?", "Angola"),
  ("Meaning 'before noon', what does the abbreviation a.m. stand for?", "ante meridiem"),
  ("In which city was the first series of Auf Wiedersehen Pet primarily set?", "Dusseldorf"),
  ("What precious gemstone is associated with the 45th wedding anniversary?", "Sapphire"),
  ("What is the fifth book of the Old Testament?", "Deuteronomy"),
  ("Other than the Sun, what is the nearest star to the Earth?", "Proxima Centauri"),
  ("Which band topped the UK album charts in 1991 with their debut LP \"Nevermind\"?", "Nirvana")
  ]